branches: ["main"]
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: minor
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - pkgRoot: packages/core
      npmPublish: true
  - - "@semantic-release/npm"
    - pkgRoot: packages/server
      npmPublish: true
  - - "@semantic-release/npm"
    - pkgRoot: packages/cli
      npmPublish: true
  - - "@semantic-release/git"
    - assets:
        - package.json
        - package-lock.json
        - packages/*/package.json
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
