name: Bug Report
description: Report a bug in the Personal Server
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start the server with `...`
        2. Send request to `...`
        3. Observe error `...`
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or logs if available.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Package version or commit SHA.
      placeholder: "0.0.1 or abc1234"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - core
        - server
        - cli
        - multiple / unsure
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node -v`.
      placeholder: "v20.11.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or logs.
    validations:
      required: false
